/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as GemsRouteImport } from './routes/gems'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MusclesRouteImport } from './routes/muscles'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SessionRouteImport } from './routes/session'
import { Route as SpotterRouteImport } from './routes/spotter'
import { Route as StreakRouteImport } from './routes/streak'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const GemsRoute = GemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MusclesRoute = MusclesRouteImport.update({
  id: '/muscles',
  path: '/muscles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotterRoute = SpotterRouteImport.update({
  id: '/spotter',
  path: '/spotter',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakRoute = StreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/gems': typeof GemsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/muscles': typeof MusclesRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/session': typeof SessionRoute
  '/spotter': typeof SpotterRoute
  '/streak': typeof StreakRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/gems': typeof GemsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/muscles': typeof MusclesRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/session': typeof SessionRoute
  '/spotter': typeof SpotterRoute
  '/streak': typeof StreakRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/gems': typeof GemsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/muscles': typeof MusclesRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/session': typeof SessionRoute
  '/spotter': typeof SpotterRoute
  '/streak': typeof StreakRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/gems'
    | '/history'
    | '/login'
    | '/muscles'
    | '/privacy'
    | '/programs'
    | '/progress'
    | '/session'
    | '/spotter'
    | '/streak'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/gems'
    | '/history'
    | '/login'
    | '/muscles'
    | '/privacy'
    | '/programs'
    | '/progress'
    | '/session'
    | '/spotter'
    | '/streak'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/gems'
    | '/history'
    | '/login'
    | '/muscles'
    | '/privacy'
    | '/programs'
    | '/progress'
    | '/session'
    | '/spotter'
    | '/streak'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  GemsRoute: typeof GemsRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MusclesRoute: typeof MusclesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ProgressRoute: typeof ProgressRoute
  SessionRoute: typeof SessionRoute
  SpotterRoute: typeof SpotterRoute
  StreakRoute: typeof StreakRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gems': {
      id: '/gems'
      path: '/gems'
      fullPath: '/gems'
      preLoaderRoute: typeof GemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscles': {
      id: '/muscles'
      path: '/muscles'
      fullPath: '/muscles'
      preLoaderRoute: typeof MusclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotter': {
      id: '/spotter'
      path: '/spotter'
      fullPath: '/spotter'
      preLoaderRoute: typeof SpotterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak': {
      id: '/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof StreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  GemsRoute: GemsRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MusclesRoute: MusclesRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ProgressRoute: ProgressRoute,
  SessionRoute: SessionRoute,
  SpotterRoute: SpotterRoute,
  StreakRoute: StreakRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
